### ISSUE TITLE
Localization of Node's own output/error messages

### ISSUE THREAD

**Issue by jasnell** [nodejs/Intl#12]
Node's error messages, help and debug output are currently not localized. I have been investigating what it would take to enable localization of Node's output. I will use this issue to track the progress of that investigation.

**Comment by kevinmartin** [comment]
Linking your issue: joyent/node#9174

My 2 cents:
- There should be an automated build process that extracts the strings and places them in centralized file(s) - Either a single language file (or multiple files, similar to Gettext domains).
  - format should be a universally acceptable format that can be imported into a tool like Transifex.
- If we use the suggested `L10N("KEY", "Fallback string")` format:
  - the build process needs to check that if the function is called in multiple places, the fallback string should be the same everywhere.
  - KEY should be in a pre-defined, specific format for consistency.
- We need to also localize stack messages.
- It would be nice if we can have a centralized place (ie. https://nodejs.org/errors/KEY?stack=...) of viewing all of these errors online with explanations and the typical way(s) to solve it.
  - Where the `stack` parameter is a language-agnostic representation of the error stack message.
  - And the entire Error message/stack can be translated to various languages on the website.
    - This is good, because if someone is running a version of node that is not localized to them, they can still see the message online in their own language.
  - This is somewhat beyond the scope of this WG, though.
  - Angular does a good job with this (minus the translation aspect), ie:

```
Error: [$injector:modulerr] http://errors.angularjs.org/1.3.15/$injector/modulerr?p0=myApp&p1=%5B%24injector%3Anomod%5D%20
```

**Comment by jasnell** [comment]
There are some additional challenges. 
1. Currently, error handling and reporting within Node is extremely inconsistent. 
2. V8's own error messages are not localized. However, Chrome doesn't seem to have a problem with this and shows localized messages so we need to investigate more about what they are doing.
3. We need to ensure that localized error messages are still easily searchable. There are two approaches I am considering: a) including a simple, non-changing identifier with each message and b) outputting both the default (english) and localized versions of each message. I am also investigating the possibility of an npm installable tool that can provide extended explanations of specific messages (e.g. something like `node-explain ERR0001` and have it output a localized description of the problem. This ties in well with the centralized place for viewing error details online.

**Comment by kevinmartin** [comment]
As far as your point 3a, I thought `KEY` was the simple, non-change identifier?

**Comment by jasnell** [comment]
Yep. We'll just need to make sure a consistent convention is used for naming the `KEY`

**Comment by kevinmartin** [comment]
As far as your point 2, I'm not much of a C++ guy, but I did find [this](https://github.com/v8/v8/blob/master/src/messages.cc). Seems like V8 uses `MessageHandler::GetLocalizedMessage`. Would this be correct?

**Comment by srl295** [comment]
initial work (backlink) https://github.com/nodejs/node/pull/3413

**Comment by srl295** [comment]
looks like this was landed in https://github.com/nodejs/node/pull/11220
with tracking at https://github.com/nodejs/node/issues/11273 

thanks @jasnell !
