### ISSUE TITLE
Investigate FS and other codepage dependencies

### ISSUE THREAD

**Issue by srl295** [nodejs/Intl#25]
In https://github.com/nodejs/node/pull/3401 it's discussed that _almost all_ fs functions assume a Unicode-supporting filesystem, specifically, that `char*` are in UTF-8. While this is somewhat common (and an ideal) picture, it's not universal. Consider how to work with this issue:
- should libuv and/or calls to it detect the encoding and convert?
  - … with a fast path for environments (OS X, Windows, others?) with a known encoding

**Comment by bnoordhuis** [comment]
Libuv treats path names as byte arrays (except on Windows) so I don't think libuv is the right place to do conversion, that logic should go into the "representation layer", i.e., node.js.

> with a fast path for environments (OS X, Windows, others?) with a known encoding

There is no platform-specific known encoding, it depends on the file system.  Libuv probably needs to grow a statvfs(2) binding that lets node.js decide what file system it's dealing with on a per-path basis.

**Comment by srl295** [comment]
https://github.com/nodejs/node/issues/3519

**Comment by srl295** [comment]
^ closing due to above
