### ISSUE TITLE
Localization of Node Live Beijing page for upcoming event

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/Intl#31]
We're hosting a Node Live event in Beijing http://live.nodejs.org/events/beijing.html May 21-22 via the Node Foundation and connecting with local groups. While we've had some great turnout at prior Live events, it would make much more sense to have the Beijing page in Mandarin as well(though my understanding is that written language is similar/same but spoken(Mandarin/Cantonese) is very different). 

Anyone have interest in helping translate the page so we could have it inline English/Mandarin? We'd be super grateful.

**Comment by kosamari** [comment]
Hey ya @hackygolucky,  @nodejs/nodejs-cn would be the one used to localize website contents. 
though not sure how it's structured after Intl working group formed. AFAIK this is for technical support of internationalization not content production.

**Comment by kosamari** [comment]
I also don't know if Node Live page is under @nodejs/website ?
When we did io.js website there was base (english) doc we need to translate & send PR to website repo. FYI.

**Comment by stevemao** [comment]
I don't think it's under https://nodejs.org/en/ and I didn't know there was a live page...

**Comment by mikeal** [comment]
Should probably be logged here https://github.com/nodejs/nodejs-zh-CN/issues

And the Node.js Live website is here https://github.com/nodejs/live.nodejs.org

**Comment by JacksonTian** [comment]
I don't know how to do it.

**Comment by XadillaX** [comment]
I don't know which repo should be chosen.

**Comment by xcatliu** [comment]
I'd like to translate the page to Mandarin, but do I need to keep both English content and Chinese content?

**Comment by hackygolucky** [comment]
It would be ideal to keep it both English and Chinese content.

**Comment by xcatliu** [comment]
Sounds good. I think I can deal with it soon.

**Comment by hackygolucky** [comment]
Done and y'all are amazing for picking this up and running with it. Big props to @xcatliu 🎉 
https://github.com/nodejs/live.nodejs.org/pull/43
