### ISSUE TITLE
Restart Intl meetings - Jan 16 2017

### ISSUE THREAD

**Issue by srl295** [nodejs/Intl#33]
Monday Jan 16th https://time.is/915am_16_Jan_2017_in_PT?Node.js_Intl_WG

Plan is for the meetings to be _monthly_.

**Comment by martinheidegger** [comment]
Which poll?

**Comment by srl295** [comment]
@martinheidegger that would help, wouldn't it. Updated, above.

**Comment by srl295** [comment]
OK- think we have a time. http://time.is/900_19_May_2016_in_PT

**Comment by srl295** [comment]
OK, i've setup the _updated_ invite here - https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MnFvY2FmY3BudWV2YW5yc3NsaXVlNWc2ajAgc3JsMjk1QG0&tmsrc=srl295%40gmail.com • the video call URL should be https://plus.google.com/hangouts/_/calendar/c3JsMjk1QGdtYWlsLmNvbQ.2qocafcpnuevanrssliue5g6j0?authuser=0

**Comment by martinheidegger** [comment]
Note: I again missed the day because the timestamp was at 1:00 in the night and it showed Friday in the google calendar. (Now it`s friday at 1 o'clock at night and I just realized that this means I only missed the meeting by 24hours ...) I wonder if this is a hint that I am really bad at internationalisation and should give up my efforts?

![screenshot 2016-05-21 00 31 48](https://cloud.githubusercontent.com/assets/914122/15433022/79d2ca2e-1eeb-11e6-8925-aa60800eaa6c.png)

**Comment by srl295** [comment]
@martinheidegger sorry to have missed you !  Does this link work- http://time.is/900_19_May_2016_in_PT should show a time 24 hours ago

**Comment by martinheidegger** [comment]
@srl295 My intelligence just didn't pick apart that Friday 1:00 means "In the night between thursday and friday". That is the usual meaning but in TV time: 0:00~6:00 are usually attributed to the previous day... again: my bad. But I do find my incompetency amusing.

**Comment by srl295** [comment]
@martinheidegger don't take it too bad — Call it an i18n occupational hazard. I orchestrated another multi-continent multi-timezone meeting … and then mis-TYPED (<-- there's the problem) the invitees email addresses.

**Comment by srl295** [comment]
Let's re-restart in early December or January?

**Comment by srl295** [comment]
OK, please fill this out with times that work for you - http://doodle.com/poll/p6exrs3qzeakq2kf 

9:00 AM PT is what worked before, which means it would need to be Monday for me. Probably a monthly meeting would be the cadence for now.   I also added 1 hour on either side just in case that works better.   If we don't get good dates, please indicates so, and we can re evaluate. Thanks!

**Comment by srl295** [comment]
9:00 AM (PT) on the 9th? https://time.is/0900_9_Jan_2017_in_PT?Intl_WG

**Comment by srl295** [comment]
Sorry I have had some illness over the new year.

Let's try again this Monday - https://time.is/915am_16_Jan_2017_in_PT?Node.js_Intl_WG
We can refine the time in the future, but I'd like to get this going again.

**Comment by srl295** [comment]
Thanks @watilde for joining. You can see the meeting minutes https://goo.gl/0LNd1n  for some of the issues we talked through.

Let's do it again… maybe next month?

**Comment by martinheidegger** [comment]
Oh man, I really need to set an alert for those meetings :man_facepalming:

**Comment by srl295** [comment]
@martinheidegger Next time.

For now: mission accomplished :100:
