### ISSUE TITLE
Clarify use of npms for icu with respect to use with Node.js

### ISSUE THREAD

**Issue by mhdawson** [nodejs/Intl#36]
The docs in npm for https://www.npmjs.com/package/full-icu  and https://www.npmjs.com/package/icu4c-data should be clarified to indicate when you should use one versus the other./

**Comment by srl295** [comment]
Fixed in https://github.com/unicode-org/icu4c-data-npm/commit/a66ab2518fd5cac4424ef475d016996f97fd05b8
