### ISSUE TITLE
i18n-it-all

### ISSUE THREAD

**Issue by martinheidegger** [nodejs/Intl#37]
Just as a casual information I would like to mention that I am working on [i18n-it-all](https://github.com/workshopper/i18n-it-all) _(A workshopper to learn about internationalization)_ By now I _kinda_ have 4 of 13 exercises finished and the others outlined in the readme's. Any input would be welcome.

**Comment by srl295** [comment]
This repo is being archived…, please feel free to reopen/link elsewhere
