### ISSUE TITLE
Feedback on README.md?

### ISSUE THREAD

**Issue by srl295** [nodejs/Intl#4]
@nodejs/tsc — please put on agenda

**Comment by kosamari** [comment]
I think word internationalization (i18n) should be defined more deeper in this doc.

the confusing point for me is the comment on "out of scope" section  `Translation of Node documentation, messages, and other materials into specific languages.`

Translation groups used i18n as sort of "project name" . When someone say "i18n" in context of node/iojs, as someone who has been working on translation team & non-native english speaker, it means docs and messages translation first.

More bullet points on what IS internationalization WG and what IS NOT is very much appreciated :)

**Comment by jasnell** [comment]
@kosamari ... the Mandate section (https://github.com/nodejs/internationalization#mandate) hopefully calls some of those details out. The `internationalization` WG's responsibility would be the _implementation_ of internationalization support (e.g. Ecma-402) within Node itself, as well as ensuring compliance with Unicode standards and other globalization efforts. This mission is distinct from that of the various `i18n` working groups that are involved with translation of various project assets such as documentation and the website.

**Comment by kosamari** [comment]
@jasnell thanks! and would appreciate the explanation in your comment included in readme :)... you know... for those of us wondering where translation people should/should not go.

**Comment by jasnell** [comment]
I'll do a PR adding that tomorrow!

**Comment by srl295** [comment]
@kosamari thanks for your feedback! You've touched on why I wrote the "out of scope" section. I know there is a large and active group of people doing such translation. That work is much appreciated, and I wanted to make it clear that this was something different.   Perhaps that should be called a "Translation WG"?

**Comment by mikeal** [comment]
> Translation WG

They do more than translations though, they also manage native language social media, events, evangelism, etc. Maybe the "Global WG" or something.

**Comment by kosamari** [comment]
yeah I haven't been able to find better word for these teams they own social media accounts, manage blogs and translate things. So it does interact with website/evangelism/ and internationalization WG when y'all need language content to fill after tool and system are in place (I assume.)

**Comment by srl295** [comment]
@mikeal Maybe "Global content"? It's sort of content vs. infrastructure. Running water vs plumbing.

@kosamari Yes, in some cases. Actually a lot of the core language content comes from http://cldr.unicode.org/ - 300 people have cast 630 thousand votes for several hundred languages in this round of input, so that would be the place to contribute content for core things like date and time formats.    But there will also be content for things like the proposal in https://github.com/joyent/node/issues/9174

**Comment by mikeal** [comment]
It's not just content, they are an active community doing more than just stuff that feeds in to the website and whatnot -- it's best not to think of them as "content producers." Maybe "Global Community WG" and call the repo just "global."

**Comment by srl295** [comment]
@mikeal That's a good point. They are not just content. I like Global Community fwiw - that shows that it's more people than technology oriented. 

And maybe that could help here- this could be the "Int'l Technology WG" or something.

**Comment by mikeal** [comment]
The only thing that might be confusing w/ "Int'l Technology WG" is that it implies broader tooling work than the scope you're going for because we also have i18n tooling in the website and doc working groups that translators are using.

Names, the single hardest problem in computer science.

**Comment by srl295** [comment]
as per TSC this repo has been renamed to _Intl_ which parallels (but is not limited to) the  `Intl` object.

**Comment by srl295** [comment]
@mikeal @kosamari is [this](https://github.com/nodejs/nodejs.org/blob/master/doc/documentation/localization/index.md) the 'homepage' of the Global Community WG in a manner of speaking?

**Comment by srl295** [comment]
Example of scope: https://github.com/nodejs/node/issues/26,  https://github.com/nodejs/io.js/issues/1494, https://github.com/nodejs/io.js/issues/2165
