### ISSUE TITLE
2017 March Intl WG meeting: Mar 27, 2017

### ISSUE THREAD

**Issue by srl295** [nodejs/Intl#40]
When: https://time.is/1400_27_Mar_2017_in_PT?Node.js_Intl_WG
Agenda:  https://goo.gl/0LNd1n 
Google hangout link: https://hangouts.google.com/call/sb46mjvfvzb2rahujsxiytmi6qe

Prev agenda: #33

**Comment by watilde** [comment]
Related link that is labelled `intl`: https://github.com/nodejs/node/pull/11464

**Comment by srl295** [comment]
Renamed this to the March meeting. Please fill in the poll  [here](http://doodle.com/poll/neezmy8ghwdtvm26)

**Comment by srl295** [comment]
OK time picked! https://time.is/1400_27_Mar_2017_in_PT?Node.js_Intl_WG

**Comment by srl295** [comment]
now on!

**Comment by srl295** [comment]
Thanks all! let's do it again next month.

**Comment by martinheidegger** [comment]
Opened docs issue on package doc: https://github.com/nodejs/docs/issues/126
