### ISSUE TITLE
Intl WG decharter?

### ISSUE THREAD

**Issue by srl295** [nodejs/Intl#45]
See ^ https://github.com/nodejs/TSC/issues/353

**Comment by srl295** [comment]
- no content in the wiki or code repo here
- 20 open issues (not counting this one)… would like to capture these if the repo is going away.

**Comment by Trott** [comment]
Based on non-response, seems like there's no objection. Closing. Feel free to re-open if that's wrong.

**Comment by srl295** [comment]
@Trott Right. No objections were heard.
