### ISSUE TITLE
Call for Participants

### ISSUE THREAD

**Issue by srl295** [nodejs/Intl#5]
Agenda item for @nodejs/tsc — please help collect participants

Also we would like the help of @nodejs/evangelism to get the word out!

**Comment by Gioyik** [comment]
How can we help? Let us know how we can make visible your work or put a highlight.

-From Evangelism group.

**Comment by yosuke-furukawa** [comment]
Evangelism Group has some localization members like me.
If you need some help, I will assist you.

**Comment by juliangruber** [comment]
I can help with german stuff for sure

**Comment by srl295** [comment]
@juliangruber @yosuke-furukawa thanks, but this group isn't for localizations or translation If you are interested, however it could be helpful.  See issue #4 - we need to clarify the wording here.  
Also, I think this WG would benefit from having a liason with the translation/localization WG - is there such a WG?

@Gioyik Thanks- clearly we need to get the `README.md` in better shape, and then try to get interested parties to join.

**Comment by srl295** [comment]
@Gioyik and everyone - I've updated the `README.md` - it talks about how this WG is for support infrastructure and not for the translation itself. Can you send out a general call for participation?

@juliangruber @yosuke-furukawa It would be great to have some localization people who are interested to be part of this WG, as long as the scope is understood. Is there a WG for people doing translations and community outreach?

**Comment by srl295** [comment]
+
- @caridy says "I can help!"
- @rwaldron 
- @KevinMartin 
- @rxaviers

**Comment by rwaldron** [comment]
Present

**Comment by kevinmartin** [comment]
I'm interested in helping with this endeavor.

**Comment by srl295** [comment]
* @rwaldron 
* @KevinMartin 
* @rxaviers

**Comment by fhemberger** [comment]
@srl295 Translations are handled in @nodejs/website and the @nodejs/iojs-\* locale groups.
@juliangruber If you're interested, drop me a note at https://github.com/nodejs/iojs-de/issues.

**Comment by gaulatti** [comment]
I wanna join you :)

**Comment by jasnell** [comment]
@rotvulpix @srl295 +1

**Comment by srl295** [comment]
@rotvulpix +1 also

**Comment by kevinmartin** [comment]
+1

**Comment by mapmeld** [comment]
I was at @srl295's talk today at the Unicode Conference and would like to learn more, be involved, and learn more being involved (what a working group can do)

I currently write some NodeJS code at the Asia Foundation. Ran into issues sorting Burmese names and other i18n issues, had to create [several modules](https://gist.github.com/mapmeld/4d1e5ebb8f68b96921d1) including a sorting function in place of Intl.Collator. Am interested in ways to support this and other Intl use-cases

**Comment by srl295** [comment]
@mapmeld +1 and lets chat!

**Comment by srl295** [comment]
@rotvulpix added you to the calendar invite - sorry it was missed before!   Any one else who isn't getting the invite please let me know.

**Comment by a0viedo** [comment]
cc @nodejs/nodejs-es

**Comment by rcotrina94** [comment]
Here! _(^_^)/ :hand:

**Comment by edsadr** [comment]
I would like to join too...  please add me to the calendar invite

**Comment by sergiolepore** [comment]
:hand:

**Comment by joconner** [comment]
@srl295 Still need help? Would love to participate.

**Comment by vrunoa** [comment]
✋ will be glad to help

**Comment by srl295** [comment]
@vrunoa @joconner @sergiolepore @edsadr @rcotrina94 all added - ping if you didnt' get the invite 
_EDIT_ Can we move the time forward an hour for this one? I had double booked myself. New time:  http://time.is/1000AM_2_Feb_2016_in_PT/ET?IntlWG

_EDIT_ Other meeting was moved - time is again http://time.is/0900AM_2_Feb_2016_in_PT/GMT/ET?NodeIntl

**Comment by vrunoa** [comment]
@srl295 sorry guys, I just realized i'm gonna be travelling to argentina on february 2, can't help. sorry again.

**Comment by chrisdickinson** [comment]
I might not be able to join myself, but it would be excellent if someone from the Docs WG could attend & relay info both ways — cc'ing @nodejs/documentation.

**Comment by stevemao** [comment]
I can help  :hand:

**Comment by srl295** [comment]
http://time.is/0900AM_2_Feb_2016_in_PT/GMT/ET?NodeIntl  Meeting is at 9am PT (click for more times)

**Comment by Knighton910** [comment]
I'll be in attendance :8ball:

**Comment by rdodev** [comment]
I would love to attend and take notes but I'll be busy helping with a
training event next couple days. Sorry to miss it.

Best,
Ruben

**Comment by srl295** [comment]
Added @kelthenoble to the invite…  
I don't have an email for @rdodev or @stevemao so please write me at `srl295＠gmail . com` and I'll set you up…

**Comment by Knighton910** [comment]
:+1: @srl295

**Comment by sergiolepore** [comment]
@srl295 sorry, I won't make it on time :disappointed: will this meeting be recorded?

**Comment by srl295** [comment]
@sergiolepore not sure how to record it. i will take notes though

**Comment by a0viedo** [comment]
@srl295 Hangouts On Air are automatically recorded, more info on how to create one [here](https://github.com/nodejs/node/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event). Also I should warn it has a limit of 15 people attending but unlimited to people watching.

**Comment by nisnardi** [comment]
hi guys, I would like to help, I'm not sure how. Let's keep in contact and please add me so I can see how I can contribute. Thanks

**Comment by ianaya89** [comment]
Hey there, I am willing to help. Please feel free to reach me for whatever is needed.

**Comment by nicolasdanelon** [comment]
Hello everybody I can help :hand:

**Comment by sfabrizio** [comment]
Hi there! I can help too.. just tell me how..

**Comment by srl295** [comment]
OK. Next meeting tomorrow- http://time.is/0900AM_16_Feb_2016_in_PT/ET/GMT/CET?NodeIntl  will try _google hangouts_ this time.

**Comment by edsadr** [comment]
Where is the hangout link? couldn't find it

2016-02-15 19:12 GMT-05:00 Steven R. Loomis notifications@github.com:

> OK. Next meeting tomorrow-
> http://time.is/0900AM_16_Feb_2016_in_PT/ET/GMT/CET?NodeIntl will try _google
> hangouts_ this time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodejs/Intl/issues/5#issuecomment-184448988.

## 

## 

Adrián Estrada
@edsadr | MedellinJS

**Comment by srl295** [comment]
hangout link is -
https://plus.google.com/hangouts/_/xcscon533kg5jflln54cwlqysia?authuser=1&hl=en-US

[

**Comment by srl295** [comment]
Trying to start meeting at the hangout link above

**Comment by srl295** [comment]
Cancelled today's. Wondering if monthly is a better cadence?

**Comment by edsadr** [comment]
would this be enough? doesn't look like we would have big progress with a monthly meeting... what about rescheduling the same week if we couldn't meet?

**Comment by martinheidegger** [comment]
Hello Everyone :hand:  I am interested in internationalisation and node.

**Comment by watilde** [comment]
I'm interesting in ECMA-402 and internationalization/localization in Node ✋

**Comment by srl295** [comment]
Meeting tomorrow? 
When: [09:00 PT, Mar 15](http://time.is/0900AM_15_Mar_2016_in_PT/ET/GMT/CET?NodeIntl) (US has, sadly, switched to DST- hit the link for time in your local time zone)
Where: [Video](https://hangouts.google.com/call/c3nyovghqzc5vmsxkduk2dhcjue) | [Agenda](https://goo.gl/0LNd1n)

**Comment by martinheidegger** [comment]
@srl295 I am in.

**Comment by martinheidegger** [comment]
Sorry for missing the meetup, I mixed up the date (thought it was tomorrow)

**Comment by srl295** [comment]
@martinheidegger one of the things we want to change is
- meet monthly
- review the agenda prior to the meeting

If I missed anyone's invite to https://node-intl.slack.com please let me know and I will invite you.

**Comment by pmdartus** [comment]
Hi, I can help as well!

**Comment by srl295** [comment]
^ Cancelling tomorrow's meeting and future. Getting a doodle together for scheduling… please let me know which days don't work and I'll omit.

**Comment by srl295** [comment]
^ A month later - please fill this out if you would like to join a new _monthly_ meeting: https://github.com/nodejs/Intl/issues/33

**Comment by andjc** [comment]
I am interested in participating, my focus is on requirements for lesser used and minority languages.

**Comment by srl295** [comment]
cc: @joconner  … and PSA:  please fill out the doodle poll here: https://github.com/nodejs/Intl/issues/33#issuecomment-257426217

**Comment by RichardLitt** [comment]
I am interested in helping out and joining the working group. My focus is also on low-resource and minority languages. (@andjc would love to connect to you about that!)

**Comment by Trott** [comment]
As we're decommissioning the actual working group, I'm going to close this. Still, there is an Intl team so if anyone wants to be added to that team (so you will get pinged when someone mentions @nodejs/Intl), leave a comment here.

Also, if there's an energetic group of people who have a clear idea of exactly what they want the working group to do, there's no reason it can't be re-chartered.

EDIT: Oh, and since this repo will likely be read-only at some point, feel free to request being added to the team by opening an issue in the nodejs/TSC repo instead.
